iiitp_1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("profile_student.urls"))
]

profile_student/urls.py
from django.urls import path
from . import views


app_name = "profile" 
urlpatterns = [
    path("", views.index, name="index"),
    path("signup/signup.html", views.signup_student, name="signup_stud"),
    path("signin/signin.html", views.signin_student, name="signin_stud"),
    path("default/index.html", views.default_index, name="def_index"),
    path("default/display/display.html", views.display_prof, name="display"),
    path("logout", views.logout_view, name="logout_view"),
    path("company_Person/Cp.html", views.company_person, name="companyperson"),
    path("company_Person/signin_cp/signin.html", views.signin_company, name="comp_signin"), 
    path("company_Person/signup_cp/signup.html", views.signup_company, name="comp_signup"),
    path("faculty_incharge", views.faculty_incharge, name="fac_in"),
    path("student_incharge", views.student_incharge, name="stu_in"),
    path("candidates", views.candi, name="cand"),
    path("default/candi", views.default_index_candi, name="def_c"),
    
]

profile_student/models.py
from django.db import models


GENDER_CHOICES = (
    (0, 'male'),
    (1, 'female'),
    (2, 'not specified'),
)
DEPT_CHOICES = (
    (0, 'cse'),
    (1, 'ece')
)

# Create your models here.
class Student(models.Model):
    name = models.CharField(max_length=64)
    #username = models.CharField(max_length=64)
    mis = models.IntegerField(primary_key=True,blank=False)
    date_of_birth = models.DateField()
    gender = models.IntegerField(choices=GENDER_CHOICES, default = 2)# models.
    gpa = models.FloatField(default=0.0)
    stream = models.IntegerField(choices=DEPT_CHOICES, default=0)
    # address = models.TextField(max_length=200, default="Address")
    email = models.EmailField(unique=True, default="example@email.com")
    mobile_number = models.IntegerField(default=000000000)
    alternate_number = models.IntegerField(default=000000000)
    # profile_pictures = models.

    def __str__(self):
        return f"{self.mis} : {self.name}"

profile_student/views.py
from django.shortcuts import render
from .models import Student
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User

# Create your views here.
def index(request):
    return render(request, "profile_student/home/index.html")

def signup_student(request):
    if request.method == "POST":
        name = request.POST["name"]
        username = request.POST["mis"]
        password = request.POST["pass"]
        repass = request.POST["re_pass"]
        agree_terms = request.POST.get("agree_terms",False)
        if agree_terms or repass == password:
            user = User.objects.create_user(username= username, password=password)
            user.save()
            return HttpResponseRedirect(reverse("profile:signin_stud"))
        else:
            return HttpResponseRedirect(reverse("profile:signup_stud"))
            
    if not request.user.is_authenticated:
        return render(request, "profile_student/home/signup/signup.html")
    else:
        return render(request, "profile_student/default/index.html")



def signup_company(request):
    if request.method == "POST":
        name = request.POST["name"]
        username = request.POST["mis"]
        password = request.POST["pass"]
        repass = request.POST["re_pass"]
        agree_terms = request.POST.get("agree_terms",False)
        if agree_terms or repass == password:
            user = User.objects.create_user(username= username, password=password)
            user.save()
            return HttpResponseRedirect(reverse("profile:comp_signin"))
        else:
            return HttpResponseRedirect(reverse("profile:comp_signup"))
            
    if not request.user.is_authenticated:
        return render(request, "profile_student/home/company_Person/signup_cp/signup.html")
    else:
        return render(request, "profile_student/default/candidate.html")

    #return render(request, "profile_student/home/company_Person/signup_cp/signup.html")



        
def signin_student(request):
    if request.method == "POST":
        username = request.POST["mis"]
        password = request.POST["your_pass"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("profile:def_index"))
        else:
            return HttpResponseRedirect(reverse("profile:signin_stud"))
    else:
        return render(request, "profile_student/home/signin/signin.html")


def signin_company(request):
    if request.method == "POST":
        username = request.POST["mis"]
        password = request.POST["your_pass"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("profile:def_c"))
        else:
            return HttpResponseRedirect(reverse("profile:comp_signin"))
    else:
        return render(request, "profile_student/home/company_Person/signin_cp/signin.html")
    #return render(request, "profile_student/home/company_Person/signin_cp/signin.html")



def default_index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("profile:signin_stud"))
    return render(request, "profile_student/default/index.html", {
        'mis':request.user.username
    })






def display_prof(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("profile:signin_stud"))
    else:
        mis = request.user.username
        student = Student.objects.filter(mis=int(mis))
        if len(student)==0:
            message = "Your profile is not updated in database."
            return render(request, "profile_student/default/display/display.html", {
                "message": message
            })
        else:
            return render(request, "profile_student/default/display/display.html", {
                "student": student
            })

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("profile:index"))

def company_person(request):
    return render(request, "profile_student/home/company_Person/Cp.html")

def faculty_incharge(request):
    return render(request, "profile_student/default/Faculty-incharge.html")

def student_incharge(request):
    return render(request, "profile_student/default/Student-incharge.html")

def candi(request):
    return render(request, "profile_student/default/candidate.html")

def default_index_candi(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("profile:comp_signin"))
    
    if request.method=="POST":
        sor = request.POST.get('quantity', 1)
        filt = request.POST["c"]
        if int(filt) == 2:
            students = Student.objects.all()
        else:
            students = Student.objects.filter(stream=int(filt))
        students = students.filter(gpa__gte = float(sor))
        
        return render(request, "profile_student/default/candidate.html", {
            "students" : students 
        })
    else:
        message="There are no students with selected criteria"
        return render(request, "profile_student/default/candidate.html", {
            "message" : message
        })

profile_student/templates/profile_student/default/Faculty-incharge.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Faculty In-charge</title>
	<link rel="stylesheet" type="text/css" href="{% static 'profile_student/default/xxx.css'%}">
</head>
<body>
	<a href="{% url 'profile:def_index' %}">Go Back</a>
	<button><a href="{% url 'profile:logout_view' %}">Log out</a></button>
	<br>
	<div>

	<table style="width:100%">
	  <tr>
	    <th>Department</th>
	    <th>Faculty In-charge</th>
	    <th>Contact</th>
	  </tr>
	  <tr>
	    <td><strong>Academics</strong></td>
	    <td>Dr Sanjeev Sharma</td>
	    <td>+91 7905391939 <br><br>sanjeevsharma@iiitp.ac.in</td>
	  </tr>
		<tr>
	    <td><strong>Administration</strong></td>
	    <td>Dr Darshan V Medhane</td>
	    <td>+91 7906159298 <br><br> darshanmv@iiitp.ac.in</td>
	  </tr>
		<tr>
	    <td><strong>HOD (CSE)</strong></td>
	    <td>Dr Tanmoy Hazra</td>
	    <td>+91 6814763148 <br><br> tanmoyhazra@iiipt.ac.in</td>
	  </tr>
		<tr>
	    <td><strong>HOD (ECE)</strong></td>
	    <td>Dr Nagendra kushwaha</td>
	    <td>+91 7566988212 <br><br> nagendra@iiitp.ac.in</td>
	  </tr>
		<tr>
	    <td><strong>Sports & Gymkhana</strong></td>
	    <td>Dr Bhupinder</td>
	    <td>+91 7905391939 <br><br>sanjeevsharma@iiitp.ac.in</td>
	  </tr>
		<tr>
	    <td><strong>Hostel</strong></td>
	    <td>Dr Nagendra kushwaha</td>
	    <td>+91 7566988212 <br><br> nagendra@iiitp.ac.in</td>
	  </tr>
		<tr>
	    <td><strong>Library</strong></td>
	    <td>Dr SP Gudi</td>
	    <td>+91 7569968423 <br><br>spgudi123@iiitp.ac.in</td>
	  </tr>
	</table>
	</div>
</body>
</html>

profile_student/templates/profile_student/default/Student-incharge.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Faculty In-charge</title>
	<link rel="stylesheet" type="text/css" href="{% static 'profile_student/default/yyy.css'%}">
</head>
<body>
	<a href="{% url 'profile:def_index' %}">Go Back</a>
	<button><a href="{% url 'profile:logout_view' %}">Log out</a></button>
	<br>
	<div>
	<table style="width:100%">
	  <tr>
	    <th>Clubs</th>
	    <th>Student In-charge</th>
	    <th>Contact</th>
	  </tr>
	  <tr>
	    <td><strong>Literature Club</strong></td>
	    <td>Uphar Bhasin</td>
	    <td>+91 7908391939 <br><br>bhasin.uphar@iiitp.ac.in</td>
	  </tr>
		<tr>
	    <td><strong>Art and Craft</strong></td>
	    <td>Vishal Pathak</td>
	    <td>+91 7906159298 <br><br> vpathak@iiitp.ac.in</td>
	  </tr>
		<tr>
	    <td><strong>Dance Club</strong></td>
	    <td>Munish Bhardwaj</td>
	    <td>+91 6814763148 <br><br> bhardwajmunish@iiipt.ac.in</td>
	  </tr>
		<tr>
	    <td><strong>Drama Club</strong></td>
	    <td>Vishal Vaibhav </td>
	    <td>+91 7566988212 <br><br> vvs@iiitp.ac.in</td>
	  </tr>
		<tr>
	    <td><strong>Sports & Gymkhana</strong></td>
	    <td>Amit Jangid</td>
	    <td>+91 8456891939 <br><br>amitjangid7@iiitp.ac.in</td>
	  </tr>
		<tr>
	    <td><strong>General Secretary</strong></td>
	    <td>Ayush Yaduvanshi</td>
	    <td>+91 7566988212 <br><br> aayushy@iiitp.ac.in</td>
	  </tr>
		<tr>
	    <td><strong>Robotics</strong></td>
	    <td>Prateek Gupta</td>
	    <td>+91 7569968423 <br><br>pg123@iiitp.ac.in</td>
	  </tr>
	</table>
	</div>
</body>
</html>

profile_student/templates/profile_student/default/candidate.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
    <a href="{% url 'profile:companyperson' %}">Go Back</a>
	<button><a href="{% url 'profile:logout_view' %}">Log out</a></button>
	<br>
    <h1>CANDIDATES DETAILS</h1>

    <form  method="POST" action="{% url 'profile:def_c' %}">
        {% csrf_token %}

        <label for="quantity">GPA (Filter):</label>
        <input type="float" id="quantity" name="quantity" min="1.0" max="10.0">
        

        <label for="c">FILTER:</label>
        <select name="c" id="cars">
          <option value="0">CSE</option>
          <option value="1">ECE</option>
          <option value="2">All</option>
        </select>
        <br><br>
        <input type="submit" value="GO">
    </form>


    {% for student in students %}
    <p><h5>MIS : {{ student.mis }}</h5></p>
    <p><h5>Name : {{ student.name }}</h5></p>
    <p><h5>Email : {{ student.email }}</h5></p>
    {% if  student.gender == 0 %}
    <p><h5>Gender : Male</h5></p>    
    {% else %}
    <p><h5>Gender : Female</h5></p>
    {% endif %}
    
    <p><h2>CGPA : {{ student.gpa }}</h2></p>

    {% if  student.stream == 0 %}
    <p><h3>DEPARTMENT : CSE</h3></p>
    {% else %}
    <p><h3>DEPARTMENT : ECE</h3></p>
    {% endif %}
    
    <hr> 

    {% empty %}
    <p>{{ message }}</p>
    {% endfor %}

</body>
</html>

profile_student/templates/profile_student/default/contact.html
{% load static %}
<!DOCTYPE HTML>
<!--
	Alpha by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<!--<title>Contact - Alpha by HTML5 UP</title>  -->
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'profile_student/default/assets/css/main.css'%}" />
	</head>
	<body class="is-preload">
		<div id="page-wrapper">

			<!-- Header -->
			<!--
				<header id="header">
					
					<nav id="nav">
						<ul>
							<li><a href="index.html">Home</a></li>
							<li>
								<a href="#" class="icon solid fa-angle-down">Layouts</a>
								<ul>
									<li><a href="generic.html">Generic</a></li>
									<li><a href="contact.html">Contact</a></li>
									<li><a href="elements.html">Elements</a></li>
									<li>
										<a href="#">Submenu</a>
										<ul>
											<li><a href="#">Option One</a></li>
											<li><a href="#">Option Two</a></li>
											<li><a href="#">Option Three</a></li>
											<li><a href="#">Option Four</a></li>
										</ul>
									</li>
								</ul>
							</li>
							<li><a href="#" class="button">Sign Up</a></li>
						</ul>
					</nav>
				</header>
			-->

			<!-- Main -->
				<section id="main" class="container medium">
					<header>
						<h2>Contact Us</h2>
						<p>Tell us what you think about our little operation.</p>
					</header>
					<div class="box">
						<form method="post" action="#">
							<div class="row gtr-50 gtr-uniform">
								<div class="col-6 col-12-mobilep">
									<input type="text" name="name" id="name" value="" placeholder="Name" />
								</div>
								<div class="col-6 col-12-mobilep">
									<input type="email" name="email" id="email" value="" placeholder="Email" />
								</div>
								<div class="col-12">
									<input type="text" name="subject" id="subject" value="" placeholder="Subject" />
								</div>
								<div class="col-12">
									<textarea name="message" id="message" placeholder="Enter your message" rows="6"></textarea>
								</div>
								<div class="col-12">
									<ul class="actions special">
										<li><input type="submit" value="Send Message" /></li>
									</ul>
								</div>
							</div>
						</form>
					</div>
				</section>

			<!-- Footer -->
				<footer id="footer">
					<ul class="icons">
						<li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
						<li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
						<li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
						<li><a href="#" class="icon brands fa-github"><span class="label">Github</span></a></li>
						<li><a href="#" class="icon brands fa-dribbble"><span class="label">Dribbble</span></a></li>
						<li><a href="#" class="icon brands fa-google-plus"><span class="label">Google+</span></a></li>
					</ul>
					<ul class="copyright">
						<li>&copy; Untitled. All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
					</ul>
				</footer>

		</div>

		<!-- Scripts -->
			<script src="{% static 'profile_student/defaultfaculty/assets/js/jquery.min.js'%}"></script>
			<script src="{% static 'profile_student/defaultfaculty/assets/js/jquery.dropotron.min.js'%}"></script>
			<script src="{% static 'profile_student/defaultfaculty/assets/js/jquery.scrollex.min.js'%}"></script>
			<script src="{% static 'profile_student/defaultfaculty/assets/js/browser.min.js'%}"></script>
			<script src="{% static 'profile_student/defaultfaculty/assets/js/breakpoints.min.js'%}"></script>
			<script src="{% static 'profile_student/defaultfaculty/assets/js/util.js'%}"></script>
			<script src="{% static 'profile_student/default/assets/js/main.js'%}"></script>

	</body>
</html>

profile_student/templates/profile_student/default/display/display.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <title>Page Title</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
</head>
<body>
    {% if message %}
    <p><strong>{{ message }}</strong></p>
    <p>Please contact Administration Department</p>
    {% else %}
    <p>Name: <strong>{{ student.name }}</strong></p>
    <p>MIS: <strong>{{ student.mis }}</strong></p>
    <p>Date of Birth: <strong>{{ student.date_of_birth }}</strong></p>
    <p>Email: <strong>{{ student.email }}</strong></p>
    <p>Mobile Number: <strong>{{ student.mobile_number }}</strong></p>
    {% endif %}
    <a href="{% url 'profile:def_index' %}">Go Back</a>
    <button><a href="{% url 'profile:logout_view' %}">Log out</a></button>
</body>
</html>

profile_student/templates/profile_student/default/index.html
{% load static %}
<!DOCTYPE HTML>
<!--
	Alpha by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>


	<head>
		<title>Team 13</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
		<link rel="stylesheet" type="text/css" href="{% static 'profile_student/default/css/style.css'%}">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha512-SfTiTlX6kk+qitfevl/7LibUOeJWlt9rbyDn92a1DqWOw9vWG2MFoays0sgObmWazO5BQPiFucnnEAjpAB+/Sw==" crossorigin="anonymous" />
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="{% static 'profile_student/default/assets/css/main.css'%}" />
	</head>

	<body class="landing is-preload">
		<div id="page-wrapper">

			<!-- Header -->
				<header id="header" class="alt">
					<h1><a href="index.html">welcome</a> by Team 13</h1>
					<nav id="nav">
						<ul>
							<li><a href="{% url 'profile:index' %}">Home</a></li>
							<li>
								<a href="#" class="icon solid fa-angle-down">Layouts</a>
								<ul>
									<li><a href="https://www.iiitp.ac.in/node/256">Directors word</a></li>
									<li><a href="contact.html">Contact</a></li>
									<!--<li><a href="https://accounts.google.com/signin/v2/identifier?continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&service=mail&sacu=1&rip=1&flowName=GlifWebSignIn&flowEntry=ServiceLogin">Webmail</a></li>  -->
									
								</ul>
							</li>
							<li><a href="{%url 'profile:fac_in'%}" class="button">Faculty Incharge</a></li>
							<li><a href="{%url 'profile:stu_in'%}" class="button">Student Incharge</a></li>
						</ul>
					</nav>
				</header>

			<!-- Banner -->
				<section id="banner">
					<h2>Indian Institute of Information Technology, Pune</h2>
					<p>IIITP family welcomes on board </p>
					<ul class="actions special">
						<li><a href="../default/display/display.html" class="button primary">Student Profile</a></li>
						<li><a href="job/jobpro/job1.html" class="button">CRDC PLACEMENT</a></li>
					</ul>
				</section>

			<!-- Main -->
					<section id="main" class="container">

					<section class="box special">
						<header class="major">
							<strong><i><h2>Hey Peeps !
							<br />
							want to explore more ?</h2>
							<p>To address the challenges faced by the Indian IT industry and growth of the domestic IT market, the Ministry of Human Resource Development (MHRD), Government of India intends to establish twenty Indian Institutes of Information Technology(IIIT), on a Not-for-profit Public Private Partnership (N-PPP) basis. The partners in setting up the IllTs would be the Ministry of Human Resource Development (MHRD), Governments of the respective States where each lllT will be established, and the industry.</p></strong></i>
						</header>
						<!--<span class="image featured"><img src="images/pic01.jpg" alt="" /></span>-->
					</section>

					<section class="box special features">
						<!--<div class="features-row">
							<section>
								<span class="icon solid major fa-bolt accent2"></span>
								<h3>STUDENT LIFE</h3>
								<p>IIITP follows international curriculum and course it provide is up to date not like any other IIITs and IITs. And encourage students to think out of the box. It has several clubs that help the students to grow their domain in the fields of Tech, Art, Culture and Sportsmanship. Having the young minds to be prepared to take up social challenges,inculcating them with leadership skills and entreprenuer skills.</p>
							
						</div>  -->
						<div class="features-row">
							<section>
								<a><i class="fa-3x fa fa-desktop" aria-hidden="true"></i></a>
								<!--<span class="icon solid major fa-cloud accent4"></span>-->
								<h3><strong><i>Computer Science Engineering</h3></strong></i>
								<p>The Institute provides all the three degrees B.Tech , M.Tech and PhD under department of Computer Science. The first of B.Tech started in 2016 , whereas M.Tech and PhD batches started in 2019.</p>
							</section>
							<section>
								<a><i class="fa-3x fa fa-microchip" aria-hidden="true"></i></a>
								<h3><strong><i>Electronics and Communication Engineering</h3></strong></i>
								<p>The Institute provides all the three degrees B.Tech , M.Tech and PhD under department of Electronics and Communication. The first of B.Tech started in 2016 , whereas M.Tech and PhD batches started in 2019...</p>
							</section>
						</div>
					</section>

                    <section class="box special">
						<h2><strong><i>CLUBS & SOCITIES
							<br />
							</h2>
							<p>A world outside classroom</p></strong></i>
							
						</header>
			
					</section>









					<div class="row">
						<div class="col-6 col-12-narrower">

							<section class="box special">
								<span class="image featured"><img src="{% static 'profile_student/default/images/pic02.jpg'%}" alt="" /></span>
								<h3>Bit legon</h3>
								<p>Elite Programming Club.</p>
								<ul class="actions special">
									<li><a href="https://linktr.ee/bitlegion" class="button alt">Learn More</a></li>
								</ul>
							</section>

						</div>
						<div class="col-6 col-12-narrower">

							<section class="box special">
								<span class="image featured"><img src="{% static 'profile_student/default/images/1.jpg'%}" alt="" /></span>
								<h3>ABHINAY </h3>
								<p>The drama society of iiitp .</p>
								<ul class="actions special">
									<li><a href="https://www.instagram.com/abhinay.iiitp/" class="button alt">Learn More</a></li>
								</ul>
							</section>

							</div>
						<div class="col-6 col-12-narrower">

							<section class="box special">
								<span class="image featured"><img src="{% static 'profile_student/default/images/vc1.jpg'%}" alt="" /></span>
								<h3>Vanity Crew</h3>
								<p>welcome to official dance club .</p>
								<ul class="actions special">
									<li><a href="#" class="button alt">Learn More</a></li>
								</ul>
							</section>

						</div>
                             <div class="col-6 col-12-narrower">

							<section class="box special">
								<span class="image featured"><img src="{% static 'profile_student/default/images/eklavya.jpg'%}" alt="" /></span>
								<h3>EKLAVYA</h3>
								<p>Official sport fest of iiitp </p>
								<ul class="actions special">
									<li><a href="https://www.instagram.com/eklavya_iiitp/" class="button alt">Learn More</a></li>
								</ul>
							</section>

							</div>


					</div>

				</section>












  <body>
    <h3>EXplore IIITP</h3>
    <!--The div element for the map -->
    <div id="map"></div>
  </body>




<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3785.388671415386!2d73.90263635000368!3d18.420653776969576!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bc2b405ac494d45%3A0xc302bc70566bb0f8!2sIndian%20Institute%20of%20Information%20Technology%2C%20Pune!5e0!3m2!1sen!2sin!4v1602401053720!5m2!1sen!2sin" width="100%" height="400px" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>

















			<!-- CTA 
				<section id="cta">

					<h2>Sign up </h2>
					<p>We welcome you to our family.</p>

					<form>
						<div class="row gtr-50 gtr-uniform">
							<div class="col-8 col-12-mobilep">
								<input type="email" name="email" id="email" placeholder="Email Address" />
							</div>
							<div class="col-4 col-12-mobilep">
								<input type="submit" value="Sign Up" class="fit" />
							</div>
						</div>
					</form>

				</section>  -->

			<!-- Footer -->
				<footer id="footer">
					<ul class="icons">
						<li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
						<li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
						<li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
						<li><a href="#" class="icon brands fa-github"><span class="label">Github</span></a></li>
						<li><a href="#" class="icon brands fa-dribbble"><span class="label">Dribbble</span></a></li>
						<li><a href="#" class="icon brands fa-google-plus"><span class="label">Google+</span></a></li>
					</ul>
					<ul class="copyright">
						<li>&copy; Untitled. All rights reserved.</li><li>Designed by: <a href="http://html5up.net">Amit meena , Ajay , Bhupendra , Mihir</a></li>
					</ul>
				</footer>

		</div>

		<!-- Scripts -->
			<script src="{% static 'profile_student/default/assets/js/jquery.min.js'%}"></script>
			<script src="{% static 'profile_student/default/assets/js/jquery.dropotron.min.js'%}"></script>
			<script src="{% static 'profile_student/default/assets/js/jquery.scrollex.min.js'%}"></script>
			<script src="{% static 'profile_student/default/assets/js/browser.min.js'%}"></script>
			<script src="{% static 'profile_student/default/assets/js/breakpoints.min.js'%}"></script>
			<script src="{% static 'profile_student/default/assets/js/util.js'%}"></script>
			<script src="{% static 'profile_student/default/assets/js/main.js'%}"></script>

	</body>
</html>